---
- name: Fetch base image and create a container out of it
  command: "buildah from --name {{ container_name }} {{ from_url }}"
  become: yes
  register: buildah_from_res
  changed_when: "buildah_from_res.rc == 0"
  failed_when: "buildah_from_res.rc == 1 and 'is already in use by' not in buildah_from_res.stderr"

- name: Set buildah from result
  set_fact:
    buildah_from: "{{ buildah_from_res.stdout }}"
  when: "buildah_from_res.stdout is defined"
...
